version: '3'
services:
  app:
    build: 
      context: ./events
      dockerfile: docker.dockerfile
    volumes:
      - .:/events
    ports:
      - "5173:5173"
    command: npm start
  api:
    build: 
      context: ./api
      dockerfile: docker.dockerfile
    volumes:
      - .:/api
    ports:
      - "3000:3000"
    command: npm start